### ISSUE TITLE
Promise pending:  `resolve` not called

### ISSUE THREAD

**Issue by braytak** [wojtekk/tar-rename#1]
The following code returns a pending Promise...
 It looks like the `tar-stream.pack` `close` event is not happening... so `resolve()` does not get called by the event listener. 

`const tr = require('tar-rename');`        
`tr({...}).then(()=>{console.log('Done!')})`

**Comment by braytak** [comment]
Supplement to my previous message... 

`tar-rename` does however do its thing , but my follow-up code in the `then` function is not executed.

**Comment by braytak** [comment]
Sorry...

**Comment by wojtekk** [comment]
Hi, thanks - you are right. I've just fixed a bug - new version: `1.0.5`.

Please reopen the issue if the problem still exists.

**Comment by braytak** [comment]
@wojtekk  Tks! Works as expected.
